language: node_js
node_js:
  - 8
  - 10
  - stable
dist: xenial
addons:
  chrome: stable
  firefox: latest
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run lint
  - npm run test
